version: '3'
services:
  db:
    container_name: db
    image: postgres:9.6.16
    platform: linux/x86_64
    volumes:
      - postgresql_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
  web:
    container_name: web
    image: diveintohacking/docker-compose-rails-6:0.0.4
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app
    environment:
      - BUNDLE_PATH=/app/vendor/bundle
    ports:
      - "3001:3000"
    depends_on:
      - db
    stdin_open: true
    tty: true

volumes:
  postgresql_data:
